services:
  - type: web
    name: beat-bkm
    runtime: ruby
    plan: free
    region: singapore
    buildCommand: bundle install
    startCommand: bundle exec puma -p $PORT
    envVars:
      - key: RACK_ENV
        value: production
      - key: GTM_CONTAINER_ID
        value: GTM-WV2DLTNM
